# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Datsercom CI

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on:
      group: Ubuntu-Runner
      labels: datsercom

    steps:
      - name: Checkout Main Branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Install nvm
        run: npm install -g nvm

      - name: Install node 18
        run: nvm install 18.16.0

      - name: Use node 18
        run: nvm use 18

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install Dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Build Website
        run: pnpm build

      - name: restart pm2
        run: pm2 restart portfolio
