# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Portfolio CI

on:
  push:
    branches: ['master']

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout Main Branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: master
  
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
  
      - name: Install Dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Build Website
        run: pnpm build

      - name: restart pm2
        run: pm2 restart portfolio